language: objective-c
osx_image: xcode7.3
xcode_sdk: macosx10.11

before_script:
    - ./bootstrap.sh

branches:
    only:
        - master

script:
    - xcodebuild test -parallelizeTargets -scheme Quill
